# Generated by Django 5.2.3 on 2025-08-05 15:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('django', 'Django Web Applications'), ('security', 'Cybersecurity Projects'), ('educational', 'Educational Content'), ('cpp', 'C++ Projects'), ('python', 'Python Scripts')], max_length=20)),
                ('github_url', models.URLField()),
                ('live_demo_url', models.URLField(blank=True, null=True)),
                ('technologies', models.CharField(max_length=300)),
                ('featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('backend', 'Backend Development'), ('frontend', 'Frontend Development'), ('security', 'Cybersecurity'), ('programming', 'Programming Languages'), ('tools', 'Tools & Platforms')], max_length=20)),
                ('proficiency', models.IntegerField(default=80)),
                ('icon_class', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
